@startuml
'https://plantuml.com/class-diagram

class Shape {
  void draw()
  void erase()
}

class Circle extends Shape{
  void draw()
  void erase()
}

class Square extends Shape{
  void draw()
  void erase()
}

class Triangle extends Shape{
  void draw()
  void erase()
}

@enduml